param(
    [string]$Output = (Join-Path $PSScriptRoot '..\loader.lua')
)

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$modules = @(
    'v2/Theme',
    'v2/Motion',
    'v2/Lucide',
    'v2/Icons',
    'v2/Util',
    'v2/Surface',
    'v2/Controls',
    'v2/Window',
    'v2/LoaderUI',
    'v2/init'
)

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('-- Generated by tools/build-loader.ps1. Do not edit by hand.')
[void]$builder.AppendLine('local __modules, __cache = {}, {}')

foreach ($name in $modules) {
    if ($name -eq 'v2/Lucide') {
        $url = 'https://raw.githubusercontent.com/notpoiu/lucide-roblox-direct/fce78a59a7d3d88849dd6c4549a2f10f351b0667/source.lua'
        $source = (Invoke-WebRequest -UseBasicParsing $url).Content
    } else {
        $path = Join-Path $root ('src\' + $name.Replace('/', '\') + '.lua')
        if (-not (Test-Path -LiteralPath $path)) {
            throw "Missing module: $path"
        }
        $source = [System.IO.File]::ReadAllText($path)
    }
    [void]$builder.AppendLine(('__modules[{0}] = function(require)' -f (ConvertTo-Json $name -Compress)))
    [void]$builder.AppendLine($source.TrimEnd())
    [void]$builder.AppendLine('end')
}

[void]$builder.AppendLine(@'
local function __require(name)
    if __cache[name] ~= nil then
        return __cache[name]
    end
    local factory = assert(__modules[name], "Unknown PureLib module: " .. tostring(name))
    local value = factory(__require)
    __cache[name] = value
    return value
end

return __require("v2/init")
'@)

$resolvedOutput = [System.IO.Path]::GetFullPath($Output)
[System.IO.File]::WriteAllText($resolvedOutput, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Built $resolvedOutput"
